### ISSUE TITLE
Installed application information

### ISSUE THREAD

**Issue by mattaojie** [fingerprintjs/fingerprintjs-pro-android#58]
`Your app is uploading users' Installed application information to ${HTTP_REQUEST} without a prominent disclosure.`
Our app was rejected by Google Play due to this issue.

**Comment by mattaojie** [comment]
I found that when I call the getVisitorId method of FingerprintJS, it triggers a permission prompt on devices running Android 11 and above, asking users to consent to view the information about installed applications. However, this information does not seem to be essential for the FingerprintJS SDK. Even if I deny this permission request, the code can still obtain the request ID and visitor ID. Google requires us to provide sufficient disclosure to users before collecting this information and to respect their choice if they refuse. For devices running Android 11 and above, we can still use the FingerprintJS code normally even if users click "deny." However, for devices running Android 10 and below, it's challenging because these versions do not automatically show a permission request dialog. This means that even if users refuse our permission request, using FingerprintJS.getVisitorId will still retrieve this information, which violates Google Play’s User Data policy. `Must be granted by the user before your app can begin to collect or access personal and sensitive user data.`

**Comment by Alexey-Verkhovsky** [comment]
Hi @mattaojie! Can you please share the device model and OS version you see that permission prompt?

**Comment by Alexey-Verkhovsky** [comment]
Also, is it the first time you publish your app? Or it was published before and Google rejected the update with SDK?

**Comment by mattaojie** [comment]
![111](https://github.com/user-attachments/assets/c1aa32e1-a8a7-4e68-8e7c-d2db7316d2d7)
Xiaomi 14, Android 14

It's strange; I tested on both Samsung and Pixel phones, but there was no such permission prompt. I upgraded Fingerprint Pro to version 2.4.0 in May this year, and then this prompt started appearing on our Xiaomi phone. However, I was able to publish versions on Google Play without any issues until last week when my new app version was rejected. Google informed me that I have only 5 days to fix this issue, or the app might be removed from Google Play. Is there a way we can avoid collecting app information while still using getVisitorId? Many of our features rely on the device ID.

**Comment by Alexey-Verkhovsky** [comment]
@mattaojie I can confirm that we also notice the same weird behaviour on some devices. This is not massive though – just several cases. Anyway we started working on removing the call with preserving functionality. We target release to the end of September. As a workaround for now – you may downgrade to v2.2.3 (in case you are not using Smart Signals, and only use Identification).

**Comment by mattaojie** [comment]
Thank you for your response.

**Comment by mattaojie** [comment]
We encountered this issue again：
com.fingerprint.android:pro:2.11.0
samsung s24, android 16

**Comment by mattaojie** [comment]
Hi,

We noticed that several recent versions of the Android SDK are accessing the installed apps list, which causes our app to fail Google Play review.

In our use case, we only use the Request ID and Visitor ID generated by the SDK. Is the app list access required for these features?

If not, do you have any plans to remove this privacy-sensitive data collection or provide an option to disable it?

Thank you.
