### ISSUE TITLE
failed to download maven dependency com.fingerprint.android:pro:2.3.4

### ISSUE THREAD

**Issue by dabitdev** [fingerprintjs/fingerprintjs-pro-android#60]
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':**********-exchange:dataBindingMergeDependencyArtifactsProductionMainnetRelease'.
> Could not resolve all files for configuration ':**********-exchange:productionMainnetReleaseRuntimeClasspath'.
   > Could not find com.fingerprint.android:pro:2.3.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://repo.maven.apache.org/maven2/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://www.jitpack.io/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://maven.singular.net/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://cdn.veriff.me/android/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
       - https://maven.pkg.github.com/**********code/wallet-kit-android/com/fingerprint/android/pro/2.3.4/pro-2.3.4.pom
     Required by:
         project :**********-exchange > com.github.checkout:frames-android:4.2.3 > com.github.checkout.frames-android:checkout-android:4.2.3 > com.github.checkout:checkout-risk-sdk-android:2.0.0

**Comment by Alexey-Verkhovsky** [comment]
Hi @dabitdev! Your build happened at the exact same moment we've had small (2 minutes) maintenance window for our Maven repository. We successfully did a lot of changes for make it operating without interruptions. This won't happen again. Sorry for the inconvenience. 🙏

**Comment by dabitdev** [comment]
Thank you for your quick message, yes the build is passing now !
